### ISSUE TITLE
fatal error resulting in no modules/submodule

### ISSUE THREAD

**Issue by robertkowalski** [robrighter/node-boilerplate#10]
i get this after 

```
$ ./bin/initproject.sh 
```

since today

```
fatal: http://github.com/LearnBoost/Socket.IO.git/info/refs not found: did you run git update-server-info on the server?
```

then alot of errors where it tries to copy the html5 boilerplate and a ls in the lib folders shows me that's nothing in it.

**Comment by robertkowalski** [comment]
fixed this one, pls pull

**Comment by jonnysamps** [comment]
I don't see any commit to the boilerplate project around your comment.  Is this fix available in the public repo?  I have just cloned and run the init script with the same bug described above.  Any help appreciated.

**Comment by robertkowalski** [comment]
seems the maintainer doesn‘t maintain the repo any more. there are to unfinished pull requests from me and another one regarding the socket.io updates and dependencies.

**Comment by robertkowalski** [comment]
*to = two. 

sry i am on mobile

**Comment by jonnysamps** [comment]
Any recommendations on how to get up and running?  Should I use NPM instead of relying on the submodules?

**Comment by robertkowalski** [comment]
You could try to merge in my pull request, run the .sh script then do:

```
$ npm install -d
```

to install dependencies like redis (either in the socket.io module dir or the root of the boilerplate).

**Comment by jonnysamps** [comment]
I must be missing something.  I did what you suggested: ran init script and then npm install -d but I am getting error when I run the npm command.  How do I merge in your changes?  Do you have a repo I can pull from?

**Comment by robertkowalski** [comment]
to merge the pull request, as i deleted my fork:

```
$ curl https://github.com/robrighter/node-boilerplate/pull/12.patch | git am --signoff

$ git apply --reject --whitespace=fix .git/rebase-apply/patch

$ git add .

$ git am --resolved
```

**Comment by robertkowalski** [comment]
after that run the initproject.sh, and try an 

```
$ npm install -d 
```

in the socket.io dir
