### ISSUE TITLE
This project seems outdated?  Start using Expressling!

### ISSUE THREAD

**Issue by niftylettuce** [robrighter/node-boilerplate#16]
Hello!

I see we have some overlap with a boilerplate for Node.js --

In addition to being compatible with node `0.6.3`, [Expressling](https://github.com/niftylettuce/expressling) is kept up to date and contains a full MVC-style framework with routes/views/auth/db/sessions.

If possible, could your watchers/contributors help to merge options/features with Expressling?

We plan to continually improve and stay updated with Expressling :-).

Hop over to #expressling in Freenode and we can have a chat!

**Comment by robrighter** [comment]
Finally got around to migrating to the newer versions. Sorry it took so long ;-)
