### ISSUE TITLE
How to update the submodules?

### ISSUE THREAD

**Issue by pyrostrex** [robrighter/node-boilerplate#4]
Sorry if this is a silly question. But because i'm really not familiar with git and i couldn't find good tutorial to go with. How do i update the submodules. What i want is the latest version. Not the one in this repository. Thanks.

**Comment by kavu** [comment]
Try something like that
`git submodule foreach git pull`

**Comment by robrighter** [comment]
In version 2 just update the package.json file to include the new dependency modules and run npm install.
