### ISSUE TITLE
Not working on Clean Install

### ISSUE THREAD

**Issue by seflless** [robrighter/node-boilerplate#6]
I tried this project out yesterday and was getting this error page when I started server.js. 
    #Header#
    The Server Encountered and Error
    :(
    Error: ENOENT, No such file or directory '/var/www/emotely.com/static/index.html'
    #Footer# 

I thought I might have messed up my environment so today I reinstalled even the operating system and started from scratch. I then only installed git, then node(built and installed), then downloaded your repo. And I still get the issue.

Any ideas? Do I need to install anything for the ejs templating system? Because I couldn't find anything related to that.

Francois

**Comment by robrighter** [comment]
Hi Francois,

What version of node are you running? I noticed last night that tracking with node master you get an error similar to this. But if you stick to a tagged release it works correctly. I am currently using node tagged release v0.2.3.

Thanks,
Rob

**Comment by seflless** [comment]
Hi Francois,

What version of node are you running? I noticed last night that tracking with node master you get an error similar to this. But if you stick to a tagged release it works correctly. I am currently using node tagged release v0.2.3.

Thanks,
Rob

**Comment by mikemee** [comment]
I just did a clean install also, to use this as my first ever node app and hit a couple of problems.

1) changed the include to:

```
, io = require('socket.io')   // was 'Socket.IO'
```

2) npm install eps

I still get a bunch of log messages thrown when I go to the root page about "no such file .../view/404.ejs.  Haven't looked through those yet.

**Comment by mikemee** [comment]
I added a 404.ejs, which was a clone of 500.ejs with the text tweaked and the line with the <%= error %> line removed. Seems to work ok now.

Many thanks for your work on this!
